# M2177.003100 Deep Learning Assignment 0<br> Part 3. PyTorch Tutorial

In [ ]:
# only colab user!
!pip install torch torchvision torchaudio

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


Adapted by Haneul Pyeon from the IPython version of the PyTorch tutorial (https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) by Soumith Chintala.


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

## Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [ ]:
import torch

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [ ]:
x = torch.empty(5, 3)
print(x)
#5x3 matrix를 만듬
#pytorch로 만들어지는 tensor는 numpy의 arraay와 비슷하게 작동하는 다차열 배열인 tensor임
#일반 array나 list는 gpu의 자동미분을 지워하지 않지만 tensor는 해줌

tensor([[-4.7426e+20,  4.4306e-41, -4.7426e+20],
        [ 4.4306e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


Construct a randomly initialized matrix:



In [ ]:
x = torch.rand(5, 3)
print(x)

#5x3을 랜덤으로 채움

tensor([[0.1390, 0.1563, 0.8274],
        [0.7974, 0.5967, 0.2097],
        [0.0892, 0.6326, 0.1350],
        [0.0274, 0.0484, 0.3498],
        [0.1342, 0.4441, 0.7595]])


Construct a matrix filled zeros and of dtype long:



In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
#5x3을 0으로 채움 + 뒤에 dtype으로 어떤 타입인지 설정 가능

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

#ones는 1로 모두 초기화
# randn_lik는 넣은 tensor와 같은 shape에 랜덤 수를 넣어서 초기화

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6171, -0.7831, -1.9426],
        [ 0.8419,  0.7790, -0.4464],
        [-1.0109, -0.1239, -0.3274],
        [ 0.1635,  1.1263, -1.0822],
        [ 0.2091, -1.4281,  0.1860]])


Get its size:



In [ ]:
print(x.size())
#shape

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

## Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [ ]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.2766, -0.6614, -1.8456],
        [ 1.4428,  0.7979, -0.0884],
        [-0.8057,  0.5048,  0.3216],
        [ 0.9498,  1.3685, -0.3224],
        [ 0.9088, -0.5031,  0.9428]])


Addition: syntax 2



In [ ]:
print(torch.add(x, y))

tensor([[ 1.2766, -0.6614, -1.8456],
        [ 1.4428,  0.7979, -0.0884],
        [-0.8057,  0.5048,  0.3216],
        [ 0.9498,  1.3685, -0.3224],
        [ 0.9088, -0.5031,  0.9428]])


Addition: providing an output tensor as argument



In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.2766, -0.6614, -1.8456],
        [ 1.4428,  0.7979, -0.0884],
        [-0.8057,  0.5048,  0.3216],
        [ 0.9498,  1.3685, -0.3224],
        [ 0.9088, -0.5031,  0.9428]])


Addition: in-place



In [ ]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.2766, -0.6614, -1.8456],
        [ 1.4428,  0.7979, -0.0884],
        [-0.8057,  0.5048,  0.3216],
        [ 0.9498,  1.3685, -0.3224],
        [ 0.9088, -0.5031,  0.9428]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [ ]:
print(x[:, 1])

tensor([-0.7831,  0.7790, -0.1239,  1.1263, -1.4281])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

#view에서 -1을 넣으면 자동으로 추론을 해서 결정됨

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [ ]:
x = torch.randn(1)
print(x)
print(x.item())
print(type(x.item()))

tensor([1.6843])
1.684291958808899
<class 'float'>


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

## Converting a Torch Tensor to a NumPy Array



In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

#nunum의 배열과 변경 가능

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [ ]:
a.add_(1)
print(a)
print(b)
#이것도 참조라서 a를 바꾸면 a를 참조하던 b도 바뀜

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

#a에 numpy array를 넣고 그걸 tensor로 변형 시켜서 b에 넣음
# 그 뒤에 a에 1씩 더해도 그걸 참조하는 b가 tensor여도 바뀜

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    #x와 같은 형태의 텐서를 생성 해 1로 채움. device는 cpu인지 gpu인지 설정하는건데 앞에서 cuda로 만듬.
    x = x.to(device)                       # or just use strings ``.to("cuda")`` x가 이미 CPU에 있을 수 있기 때문에, .to(device)를 사용하여 x를 GPU로 이동시킵니다.
    z = x + y # 이제 x와 y는 모두 gpu에 있음. 즉 이 연산은 gpu에서 돌아감
    print(z)
    #PyTorch에서는 텐서가 GPU에 있으면 자동으로 CPU로 복사하지 않고 출력할 수 없습니다. 하지만 PyTorch는 출력 시 자동으로 GPU에서 CPU로 텐서를 복사하여 출력합니다.

    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2.6843], device='cuda:0')
tensor([2.6843], dtype=torch.float64)



Autograd: Automatic Differentiation
===================================

Central to all neural networks in PyTorch is the ``autograd`` package.
Let’s first briefly visit this, and we will then go to training our
first neural network.


The ``autograd`` package provides automatic differentiation for all operations
on Tensors. It is a define-by-run framework, which means that your backprop is
defined by how your code is run, and that every single iteration can be
different.

Let us see this in more simple terms with some examples.

Tensor
--------

``torch.Tensor`` is the central class of the package. If you set its attribute
``.requires_grad`` as ``True``, it starts to track all operations on it. When
you finish your computation you can call ``.backward()`` and have all the
gradients computed automatically. The gradient for this tensor will be
accumulated into ``.grad`` attribute.

To stop a tensor from tracking history, you can call ``.detach()`` to detach
it from the computation history, and to prevent future computation from being
tracked.

To prevent tracking history (and using memory), you can also wrap the code block
in ``with torch.no_grad():``. This can be particularly helpful when evaluating a
model because the model may have trainable parameters with
``requires_grad=True``, but for which we don't need the gradients.

There’s one more class which is very important for autograd
implementation - a ``Function``.

``Tensor`` and ``Function`` are interconnected and build up an acyclic
graph, that encodes a complete history of computation. Each tensor has
a ``.grad_fn`` attribute that references a ``Function`` that has created
the ``Tensor`` (except for Tensors created by the user - their
``grad_fn is None``).

If you want to compute the derivatives, you can call ``.backward()`` on
a ``Tensor``. If ``Tensor`` is a scalar (i.e. it holds a one element
data), you don’t need to specify any arguments to ``backward()``,
however if it has more elements, you need to specify a ``gradient``
argument that is a tensor of matching shape.



Create a tensor and set ``requires_grad=True`` to track computation with it



In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
#requires_grad=True 이거는 계산을 추적

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Do a tensor operation:



In [ ]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


``y`` was created as a result of an operation, so it has a ``grad_fn``.



In [ ]:
print(y.grad_fn)
# pytorch는 텐서에 적용된 모든 연산을 기록하여 계산 그래프를 내부에서 자동으로 만드는데 이 그래프는 나중에 자동미분(autograd)하는데 사용됨
# grad_fn은 바로 이전 연산만 가리키고, 전체 연산 체인은 이 그래프를 따라 거슬러 올라가면서 추적됨
# 여기서 출력된 Add는 위에서 더한거를 의미하고 Backward는 기울기를 계산할때 사용되는 역전파 함수임을 나타냄

Do more operations on ``y``



In [ ]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
flag in-place. The input flag defaults to ``False`` if not given.



In [ ]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
#a.requires_grad는 기울기를 계산하고 저장하기 위해 추적하는지 물어봄(자료형은 Boolean). 지금은 설정을 안 해서 기본값인 False가 나옴
a.requires_grad_(True)
#이걸 통해 기울기를 계산하고 저장하기 위해 추적을 시작함
print(a.requires_grad)
#위에서 True로 만들어서 추적을 시작하고 이건 True를 리턴함.
b = (a * a).sum()
# b에 a*a를 하고 sum으로 모두 더함
print(b.grad_fn)
print()
print(b)

# 코드가 이미 "목표 f의 최종 산출물인 b를 Loss로 간주하고, 이를 최소화하기 위해 a를 수정한다"
# 라는 최적화 목표를 암묵적으로 정의한 것입니다.

False
True

tensor(275.3594, grad_fn=<SumBackward0>)


Gradients
---------
Let's backprop now.
Because ``out`` contains a single scalar, ``out.backward()`` is
equivalent to ``out.backward(torch.tensor(1.))``.





> Add blockquote





In [ ]:
out.backward()
# 1. bakcward()가 호출되면 out에 기록된 grad_fn을 따라 생성된 역순으로 계산 그래프를 탐색.
# 2. grad_fm는 각각 연산에 대한 미분(기울기)를 가지고 있는데. 미적분의 연쇄 법칙을 적용하여 기울기를 이전 텐서(노드)로 전달
# 3. 계산된 기울기 값은 해당 텐서의 .grad 속성에 더해짐(누적)
# 주의: 기울기가 누적되기 때문에, 새로운 배치(Batch)로 학습을 시작할 때마다 이전 기울기를 지우기 위해 **optimizer.zero_grad()**를 먼저 호출해야 합니다.

#**Backpropagation (역전파)**는 **신경망(neural network)**의 학습 과정에서 중요한 알고리즘으로,
# 즉 록된 모든 연산에 대한 미분(기울기)을 역순으로 적용시키고, 그 결과를 학습 대상 텐서의 .grad 속성에 누적시키는 과정
# 여기서 최소화를 자동으로 해주는데 계산을 하고 기울기를 수정하는데 어느방향으로 어느정도 수정을 해야하는지를 자동으로 계산해서 누적시켜줌
# 최소화를 최적화랑 햇갈리면 안됨. 최적화는 경사 하강법(gradient dscent)같은 알고리즘을 구현해서 업데이트 해야함

Print gradients d(out)/dx




In [ ]:
print(x)
print()
print(x.grad)
#grad(기울기)는 미분의 결과로, 손실 함수가 가중치나 입력에 대해 얼마나 민감한지를 나타냅니다.
#딥러닝에서는 **경사 하강법(Gradient Descent)**을 사용하여 모델의 가중치와 파라미터를 업데이트합니다.
#이때 사용되는 기울기는 미니배치 또는 전체 데이터셋에 대해 계산된 손실 함수의 미분값입니다

#모든 요소에 대한 기울기가 4.5라는 것은, 어떤 요소를 아주 조금 증가시키면,
#최종 손실(L)이 4.5배의 비율로 증가한다는 것을 의미합니다.

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


You should have got a matrix of ``4.5``. Let’s call the ``out``
*Tensor* “$o$”.
We have that $o = \frac{1}{4}\sum_i z_i$,
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.
Therefore,
$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$, hence
$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.



You can also stop autograd from tracking history on Tensors
with ``.requires_grad=True`` either by wrapping the code block in
``with torch.no_grad():``



In [ ]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
	print((x ** 2).requires_grad)
 #**torch.no_grad()**는 no_grad 컨텍스트 매니저입니다. 이 블록 안에서 이루어지는 모든 텐서 연산은 기울기 추적을 비활성화합니다.

True
True
False


Or by using ``.detach()`` to get a new Tensor with the same
content but that does not require gradients:



In [ ]:
print(x.requires_grad)
y = x.detach() # .detach() PyTorch에서 텐서의 기울기 추적을 끊는 함수입니다.
print(y.requires_grad)
print(x.eq(y).all())
# x.eq는 x와 y가 모양이 같을때 모든 요소별로 비교를 하고 True나 False를 값으로 갖는
# boolean tensor를 새로 생성함. .all은 앞에 있는게 모두 True면 True, 하나라도 False면 False를 리턴


#이 함수는 기울기 계산 그래프에서 텐서를 **분리(detach)**시켜, 더 이상 **역전파(backpropagation)**에서 이 텐서가 기여하지 않도록 만듭니다.

True
False
tensor(True)


**Read Later:**

Document about ``autograd.Function`` is at
https://pytorch.org/docs/stable/autograd.html#function




Neural Networks
===============

Neural networks can be constructed using the ``torch.nn`` package.

Now that you had a glimpse of ``autograd``, ``nn`` depends on
``autograd`` to define models and differentiate them.
An ``nn.Module`` contains layers, and a method ``forward(input)``\ that
returns the ``output``.


A typical training procedure for a neural network is as follows:

- Define the neural network that has some learnable parameters (or
  weights)
- Iterate over a dataset of inputs
- Process input through the network
- Compute the loss (how far is the output from being correct)
- Propagate gradients back into the network’s parameters
- Update the weights of the network, typically using a simple update rule:
  ``weight = weight - learning_rate * gradient``

Define the network
------------------

Let’s define this network:



위에 내용을 번역함

네트워크 정의 (가중치 설정): 학습을 시작하기 위해 nn.Module 클래스를 상속받아 모델 구조(레이어)를 정의합니다. 이때, 모델 내부의 모든 가중치(weight) 텐서는 자동으로 requires_grad=True 속성을 가지게 됩니다.

데이터 반복: 전체 데이터셋에서 배치(Batch) 단위로 데이터를 불러옵니다.

순전파: 입력 데이터가 모델의 forward() 함수를 통과하며 예측값(y
pred
​
 )을 생성합니다.

4-6 단계: 오류 측정 및 수정 (역전파와 최적화)
손실 계산: 예측값(y
pred
​
 )과 실제 정답(y
true
​
 )을 비교하여 **손실(Loss)**을 계산합니다. 이 Loss는 $\texttt{backward()}$의 출발점이 됩니다.

기울기 역전파: $\texttt{loss.backward()}$를 호출하여 $\texttt{autograd}$가 **계산 그래프를 역추적**하며 손실에 대한 모든 가중치의 기울기($\frac{\partial \text{Loss}}{\partial \text{Weight}}$)를 계산하고 .grad 속성에 저장합니다.

가중치 업데이트 (최적화): 옵티마이저(optimizer)를 사용하여 경사 하강법 규칙(weight=weight−η⋅gradient)에 따라 가중치 값을 실제로 변경합니다. 이로써 모델은 다음 반복에서는 더 나은 예측을 할 수 있게 됩니다.

---------------------------------------
여기부터 DL 신경망 설명
------------------------------------
1단계: 모델 정의 (신경망과 가중치)
딥러닝을 시작하기 위해 가장 먼저 하는 일은 문제를 풀 **"도구"**를 만드는 것입니다.

신경망 (Neural Network): 문제를 풀기 위해 설계된 수학적 구조입니다. 입력(X)을 받아서 복잡한 계산을 거쳐 출력(Y
pred
​
 )을 내보내는 함수라고 생각하시면 됩니다.

가중치 (Weight)와 편향 (Bias): 신경망이 학습을 통해 조정해야 하는 모든 기준점 또는 파라미터입니다. 이 값들이 바로 모델의 기억이자 지식입니다. PyTorch에서는 이 가중치 텐서들을 $\texttt{requires_grad=True}$로 설정하여 **'학습 대상'**임을 표시합니다.


2단계: 데이터 준비 (입력과 정답)
모델을 학습시키려면 '문제와 정답'이 필요합니다.

입력 데이터 (X): 모델에게 보여줄 문제(예: 고양이 사진, 문장 등)입니다.

정답 (Label, Y
true
​
 ): 입력 데이터에 대한 실제 정답입니다 (예: "고양이", "긍정").

배치 (Batch): 학습을 효율적으로 하기 위해 전체 데이터를 한 번에 넣지 않고, 몇 개씩 묶어서 처리하는 덩어리입니다.


3단계: 순전파 (Forward Pass)
모델이 문제를 푸는 단계입니다.

순전파 (Forward Pass): 입력 데이터(X)가 신경망의 첫 번째 층부터 마지막 층까지 앞으로 흘러가면서 계산됩니다. 이 과정을 통해 모델의 **예측값 (Y
pred
​
 )**이 나옵니다.

torch.nn.Module.forward(): PyTorch에서 이 순전파 로직을 정의하는 함수입니다.


4단계: 손실 계산 (Loss)
모델이 낸 답이 얼마나 틀렸는지 측정합니다.

손실 함수 (Loss Function, L): 예측값(Y
pred
​
 )과 정답(Y
true
​
 ) 사이의 오차 크기를 하나의 스칼라 값으로 계산하는 함수입니다.

예시: MSE(평균 제곱 오차), Cross-Entropy Loss 등.

목표: 학습의 궁극적인 목표는 이 **손실 값을 최소화(Minimize)**하는 것입니다. 손실이 낮을수록 모델의 예측 정확도가 높아집니다.


5단계: 역전파 (Backward Pass)
오류를 바탕으로 스스로를 수정하는 방법을 찾는 단계입니다. 이 과정이 딥러닝 학습의 핵심입니다.

기울기 (Gradient): 손실 함수(L)를 **각 가중치(W)**로 미분한 값 $\left(\frac{\partial L}{\partial W}\right)$입니다. 이 값은 **"특정 가중치를 조정했을 때 손실이 얼마나, 어느 방향으로 변할지"**를 알려줍니다.

역전파 (Backpropagation): $\texttt{loss.backward()}$를 호출하여, 최종 손실에서부터 네트워크를 **거꾸로**($\leftarrow$) 거슬러 올라가며 모든 가중치에 대한 기울기를 자동으로 계산하고 W.grad 속성에 누적시키는 알고리즘입니다.


6단계: 최적화 (Optimization)
찾아낸 방법대로 실제로 가중치를 수정하는 단계입니다.

옵티마이저 (Optimizer): 계산된 기울기 값을 사용하여 가중치(W)를 실제로 업데이트하는 알고리즘입니다 (예: SGD, Adam).

학습률 (Learning Rate, η): 기울기 방향으로 얼마나 큰 폭으로 가중치를 수정할지 결정하는 값입니다. 학습의 속도를 결정합니다.

가중치 업데이트: 옵티마이저는 다음 규칙에 따라 가중치를 수정합니다. → Weight
new
​
 =Weight
old
​
 −η×Gradient

$\texttt{optimizer.zero_grad()}$로 이전 기울기를 초기화한 후, $\texttt{optimizer.step()}$을 호출하여 가중치를 실제로 변경합니다.

이 6단계를 수천, 수만 번 반복하면, 모델은 점차 손실이 최소화되는 방향으로 가중치를 수정해나가며 성능이 좋아지게 됩니다.

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module): #Net은 **nn.Module**을 상속받은 신경망 클래스입니다. nn.Module은 PyTorch에서 모든 신경망 모델을 정의할 때 기본으로 상속해야 하는 클래스입니다.

    def __init__(self):
        super(Net, self).__init__() # 부모 클래스인 nn.Module의 생성자를 호출하여 PyTorch 모듈 시스템을 초기화합니다.
        # an affine operation: y = Wx + b
        self.linear = nn.Linear(10, 5) #이 모델의 핵심 연산인 선형 계층(Linear Layer)을 정의합니다.
        #입력 크기 10: 10개의 특성(feature)을 입력으로 받고.
        #출력 크기 5: 5개의 특성(feature)을 출력으로 내보냄

#여기서 init은 신경망이 사용할 모든 계층(Layer), 함수, 모듈 등을 변수로 선언하고 모두 초기

# nn.Module을 상속받으면 반드시 forward를 구현해야함
    def forward(self, x):
        x = self.linear(x)
        return x


net = Net()
print(net)

Net(
  (linear): Linear(in_features=10, out_features=5, bias=True)
)


You just have to define the ``forward`` function, and the ``backward``
function (where gradients are computed) is automatically defined for you
using ``autograd``.
You can use any of the Tensor operations in the ``forward`` function.

The learnable parameters of a model are returned by ``net.parameters()``



In [ ]:
params = list(net.parameters())
# **net.parameters()**는 **모델 net**의 학습 가능한 파라미터들을 반환하는 메서드입니다.
#**parameters()**는 모델에 정의된 모든 파라미터 (예: 가중치, 편향)를 generator 객체로 반환합니다.
print(params)
print()
print(params[0].size())
print()
print(params[1].size())
#params[0]은 입력노드 10개와 출력노드 5개의  wiegth들이 들어있음
#params[1]에는 출력노드 5개의 각각 더해지는 편향(bias)값이 들어있음

[Parameter containing:
tensor([[ 0.1094, -0.1889, -0.0525, -0.1926, -0.2197, -0.0575, -0.0369, -0.2842,
          0.0731, -0.3085],
        [ 0.3112,  0.2729,  0.1903,  0.2471,  0.2097, -0.3096, -0.2644,  0.0038,
          0.1763, -0.2907],
        [-0.1260, -0.1385,  0.1964,  0.0931, -0.0920, -0.2956,  0.0657, -0.2518,
         -0.0492, -0.0997],
        [ 0.0464, -0.1110,  0.0122,  0.1156, -0.2622, -0.2105, -0.2376, -0.0584,
          0.0248, -0.1641],
        [-0.3005,  0.0038, -0.2017, -0.0434, -0.1977, -0.3032,  0.1196,  0.2116,
         -0.1405,  0.1991]], requires_grad=True), Parameter containing:
tensor([ 0.2502,  0.0396,  0.2891, -0.1592,  0.0655], requires_grad=True)]

torch.Size([5, 10])

torch.Size([5])


Let's try a random 1x10 input.
Note: expected input size of this net is 10.

In [ ]:
input = torch.randn(1, 10)
out = net(input)
print(out)
#위에서 초기화 한 신경망 모델에 랜덤 데이터 10개를 통과시켜 계산해보는 과정(순전파, Forward Pass)
# 신경망 모델의 parameter(weight, bias)를 기준으로 input data를 넣어 계산해 본 값이 out에 들어감
# 근데 신경망 모델이 아직 학습을 하지 않았기 때문에 무작위로 나옴

tensor([[0.9654, 1.1673, 0.8522, 0.8924, 0.2093]], grad_fn=<AddmmBackward0>)


<div class="alert alert-info"><h4>Note</h4><p>``torch.nn`` only supports mini-batches. The entire ``torch.nn``
    package only supports inputs that are a mini-batch of samples, and not
    a single sample.

    For example, ``nn.Linear`` will take in a 2D Tensor of
    ``nSamples x input_size``.

    If you have a single sample, just use ``input.unsqueeze(0)`` to add
    a fake batch dimension.</p></div>

Before proceeding further, let's recap all the classes you’ve seen so far.

**Recap:**
  -  ``torch.Tensor`` - A *multi-dimensional array* with support for autograd
     operations like ``backward()``. Also *holds the gradient* w.r.t. the
     tensor.
  -  ``nn.Module`` - Neural network module. *Convenient way of
     encapsulating parameters*, with helpers for moving them to GPU,
     exporting, loading, etc.
  -  ``nn.Parameter`` - A kind of Tensor, that is *automatically
     registered as a parameter when assigned as an attribute to a*
     ``Module``.
  -  ``autograd.Function`` - Implements *forward and backward definitions
     of an autograd operation*. Every ``Tensor`` operation creates at
     least a single ``Function`` node that connects to functions that
     created a ``Tensor`` and *encodes its history*.

**At this point, we covered:**
  -  Defining a neural network
  -  Processing inputs

**Still Left:**
  -  Computing the loss and calling backward
  -  Updating the weights of the network

Loss Function
-------------
A loss function takes the (output, target) pair of inputs, and computes a
value that estimates how far away the output is from the target.

There are several different
`loss functions <https://pytorch.org/docs/nn.html#loss-functions>`_ under the
nn package .
A simple loss is: ``nn.MSELoss`` which computes the mean-squared error
between the input and the target.

For example:



네, 해당 내용을 번역하고 초심자가 이해하기 쉽게 해설을 덧붙여 설명해 드릴게요.
​📝 참고: torch.nn은 미니배치만 지원합니다
​torch.nn 패키지 전체는 단일 샘플이 아닌, 샘플들의 **미니배치(mini-batch)**만을 입력으로 지원합니다.
​예를 들어, nn.Linear는 (샘플 수, 입력 크기) 형태의 2D 텐서를 입력으로 받습니다.
​만약 단일 샘플만 있다면, input.unsqueeze(0)를 사용해서 가짜 배치 차원을 추가해야 합니다.
​해설
​신경망을 훈련시킬 때는 보통 데이터를 한 개씩 처리하지 않고, 여러 개를 한 묶음(배치, batch)으로 만들어 처리합니다. 이는 계산 효율성을 높이고 모델 학습을 안정적으로 만들기 때문입니다.
​미니배치 (Mini-batch): 전체 데이터셋을 한 번에 처리하기엔 너무 크기 때문에, 작은 묶음으로 나눈 것을 의미합니다.
​왜 단일 샘플은 안되나요?: torch.nn의 레이어들은 기본적으로 여러 샘플이 한 번에 들어올 것을 가정하고 설계되었습니다. 예를 들어 데이터 1개를 [1, 2, 3] 형태로 넣으면 에러가 발생할 수 있습니다.
​input.unsqueeze(0): 이 코드는 텐서에 차원을 하나 추가해줍니다. 단일 데이터 [1, 2, 3] (1차원 벡터)를 [[1, 2, 3]] (2D 텐서)처럼 "1개의 샘플을 가진 배치" 형태로 바꿔주는 역할을 합니다. 즉, 샘플 1개짜리 미니배치를 만들어주는 것이죠.
​🧠 지금까지 배운 클래스 요약
​torch.Tensor
​backward()와 같은 자동 미분(autograd) 기능을 지원하는 다차원 배열입니다. 또한, 텐서에 대한 기울기(gradient)를 저장합니다.
​해설: PyTorch의 가장 기본적인 데이터 단위입니다. NumPy의 배열과 비슷하지만, 여기에 더해 계산 과정을 기록하고, 이 기록을 바탕으로 미분(기울기 계산)을 자동으로 수행하는 강력한 기능이 포함되어 있습니다. 학습에 필요한 기울기 값이 .grad 속성에 저장됩니다.
​nn.Module
​신경망 모듈입니다. 파라미터(가중치)들을 편리하게 감싸는(encapsulating) 방법이며, GPU로 옮기거나, 내보내고, 불러오는 등의 보조 기능을 제공합니다.
​해설: 모든 신경망 모델의 기본 뼈대가 되는 클래스입니다. 우리가 만들 신경망의 레이어(층)들을 이 nn.Module 클래스 안에 변수로 정의하고, forward 메소드에서 이 레이어들을 어떻게 연결해서 계산할지 순서를 정해줍니다. 신경망을 하나의 부품처럼 편리하게 관리할 수 있게 해줍니다.
​nn.Parameter
​Module의 속성(attribute)으로 할당될 때 자동으로 파라미터로 등록되는 특별한 종류의 텐서입니다.
​해설: Tensor와 거의 같지만, nn.Module에 nn.Parameter로 감싸서 변수를 할당하면 PyTorch가 "아, 이것은 학습을 통해 값이 계속 바뀌어야 하는 가중치(weight)나 편향(bias)이구나!"라고 인식합니다. 이렇게 등록된 값들만 나중에 기울기 계산과 업데이트의 대상이 됩니다.
​autograd.Function
​자동 미분 연산의 순전파(forward)와 역전파(backward) 정의를 구현합니다. 모든 Tensor 연산은 최소 하나 이상의 Function 노드를 생성하여, 해당 Tensor를 만든 함수와 연결하고 그 기록(history)을 인코딩합니다.
​해설: PyTorch의 자동 미분 기능의 핵심입니다. 우리가 텐서로 덧셈, 곱셈 등의 연산을 할 때마다, PyTorch는 내부적으로 Function 객체를 만들어 "이 계산은 어떤 연산으로 이루어졌다"는 것을 기록합니다. 이 기록 덕분에 나중에 backward()를 호출했을 때, 연산의 역사를 거슬러 올라가며 미분의 연쇄 법칙(chain rule)을 적용해 기울기를 자동으로 계산할 수 있습니다.
​🎯 남은 과정
​지금까지 우리는 신경망을 정의하고 입력을 처리하는 방법을 배웠습니다. 이제 남은 과정은 다음과 같습니다.
​손실(Loss) 계산 및 역전파 호출
​신경망의 가중치(weights) 업데이트
​📉 손실 함수 (Loss Function)
​손실 함수는 (모델의 출력, 실제 정답) 쌍을 입력으로 받아, 출력이 정답으로부터 얼마나 멀리 떨어져 있는지 측정하는 값을 계산합니다.
​nn 패키지에는 여러 종류의 손실 함수들이 있습니다.
간단한 예로, **nn.MSELoss**는 입력과 정답 사이의 **평균 제곱 오차(Mean Squared Error)**를 계산합니다.
​해설
손실 함수란?: 모델이 내놓은 예측값이 실제 정답과 얼마나 다른지(얼마나 틀렸는지)를 나타내는 점수입니다. 이 점수(손실 값)가 크면 모델이 많이 틀렸다는 뜻이고, 작으면 예측을 잘했다는 뜻입니다. 딥러닝 학습의 목표는 이 손실 값을 가능한 한 0에 가깝게 만드는 것입니다.
nn.MSELoss (평균 제곱 오차): 가장 대표적인 손실 함수 중 하나로, 주로 회귀(regression) 문제에서 사용됩니다. 계산 방식은 다음과 같습니다.
​각 데이터에 대해 (예측값 - 정답)으로 오차를 구합니다.
​오차를 제곱합니다. (부호를 없애고, 오차가 클수록 패널티를 더 많이 주기 위함)
​모든 데이터의 제곱 오차를 더한 뒤, 데이터 개수로 나누어 평균을 냅니다.
​수식으로는 다음과 같이 표현할 수 있습니다.
Loss = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2

In [ ]:
output = net(input)
target = torch.randn(5)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()
# MSELoss는 예측값과 실제값 간의 차이를 제곱하여 평균을 구하는 손실 함수입니다.
# 주로 회귀 문제에서 모델의 예측값과 실제값 간의 오차를 측정하는 데 사용됩니다.

loss = criterion(output, target) #위에 만든 MSELoss를 통해 output과 target의 손실(loss)를 만듬
print(loss)
#여기서는 loss값을 만들기 위해 위에서 만든 input을 net에 넣어보고 target값을 랜덤으로 넣어서 loss를 임의로 만들어봄

tensor(2.2601, grad_fn=<MseLossBackward0>)


when we call ``loss.backward()``, the whole graph is differentiated
w.r.t. the loss, and all Tensors in the graph that has ``requires_grad=True``
will have their ``.grad`` Tensor accumulated with the gradient.

For illustration, let us follow a few steps backward:



In [ ]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
#MSELoss 함수는 (예측값, 실제값) 두 개의 입력을 받았으므로, next_functions에는 두 입력의 "역사"가 담겨 있습니다.
#next_funtions[0]에는 예측값, [1]에는 실제값이 들어있음
#모델의 예측값은 신경망의 마지막 Linear 레이어를 통과해서 나왔을 것

Backprop
--------
To backpropagate the error all we have to do is to ``loss.backward()``.
You need to clear the existing gradients though, else gradients will be
accumulated to existing gradients.


Now we shall call ``loss.backward()``, and have a look at conv1's bias
gradients before and after the backward.



In [ ]:
#오류를 역전파하려면 loss.backward()를 호출하기만 하면 됩니다. 단, 기존 그래디언트를 지워야 합니다. 그렇지 않으면 그래디언트가 기존 그래디언트에 누적됩니다.
net.zero_grad()     # 모델의 모든 파라미터에 대한 gradiant를 초기화
#gradiant를 초기화 하지 않으면 이전 배치에서의 기울기가 현재 배치에 대해 계산된 기울기에 누적되어 잘못된 업데이트가 일어날 수 있습니다.
print('linear.bias.grad before backward')
print(net.linear.bias.grad) #Linear 레이어의 **편향(bias)**에 대한 기울기를 출력합니다.

loss.backward() #backward(역전파)는 메모리 효율을 위해 그래프를 구성하는 중간 결과들을 해제함. 그래서 동일한 그래프에 한번만 할 수 있음.
#loss.backward()가 성공적으로 실행되어 그래디언트 계산이 완료되면, PyTorch는 기본 설정에 따라 그래디언트 계산에 더 이상 필요하지 않은 이러한 중간 결과들을 메모리에서 해제합니다.
#그런데 다시 실행하게 되면 메모리를 지워버렸기 때문에 오류가 뜸.
#**loss.backward()**는 **역전파(backpropagation)**를 수행하여, **손실(loss)**에 대한 **기울기(gradient)**를 계산합니다.
#이때 계산된 기울기는 각 레이어의 파라미터(예: 가중치와 편향)에 대해 저장됩니다.
#**net.linear.bias.grad**는 이제 편향에 대한 기울기를 저장하게 됩니다.

print('linear.bias.grad after backward')
print(net.linear.bias.grad)

linear.bias.grad before backward
None
linear.bias.grad after backward
tensor([ 0.6466,  1.0992,  0.4191,  0.0473, -0.0629])


Now, we have seen how to use loss functions.

**Read Later:**

  The neural network package contains various modules and loss functions
  that form the building blocks of deep neural networks. A full list with
  documentation is `here <https://pytorch.org/docs/nn>`_.

**The only thing left to learn is:**

  - Updating the weights of the network

Update the weights
------------------
The simplest update rule used in practice is the Stochastic Gradient
Descent (SGD):

     ``weight = weight - learning_rate * gradient``

We can implement this using simple Python code:

.. code:: python

    learning_rate = 0.01
    for f in net.parameters():
        f.data.sub_(f.grad.data * learning_rate)

However, as you use neural networks, you want to use various different
update rules.
To enable this, we built a small package: ``torch.optim`` that
implements all these methods. Using it is very simple:



In [ ]:
import torch.optim as optim #pytorch의 최적화(Optimizeation) 도구들이 있음

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01) #optim.SGD는 확률적 경사 하강법을 사용
#net.parameters()는 신경망(net)의 모든 weight와 bias들을 전달(위에서 만든거 사용). lr=0.01은 학습률(Learning Rate)를 0.01로 설정
# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
#pytorch는 기본적으로 이전에 계산된 기울기(gradient)를 누적하는데 새로운 배치를 처리하기 위해 모두 0으로 초기화
output = net(input)
#net 모델에 input을 넣음 - 순전파(forward pass)
loss = criterion(output, target) # net에 넣어서 계산된 결과를 target과 비교하며 Loss를 계산
loss.backward() # backward(역전파) 계산된 loss를 net을 거꾸로 거스러 올라가며 각 매개변수에 대한 loss의 gradient를 계선해 gradient를 만듬
optimizer.step()    # Does the update 매개변수 업데이트 이전에 계산된 gradient와 learning rate를 사용하여 gradient와 bias를 업데이트


.. Note::

      Observe how gradient buffers had to be manually set to zero using
      ``optimizer.zero_grad()``. This is because gradients are accumulated
      as explained in the `Backprop`_ section.




Training a Classifier
=====================

This is it. You have seen how to define neural networks, compute loss and make
updates to the weights of the network.

Now you might be thinking,

What about data?
----------------

Generally, when you have to deal with image, text, audio or video data,
you can use standard python packages that load data into a numpy array.
Then you can convert this array into a ``torch.*Tensor``.

-  For images, packages such as Pillow, OpenCV are useful
-  For audio, packages such as scipy and librosa
-  For text, either raw Python or Cython based loading, or NLTK and
   SpaCy are useful

Specifically for vision, we have created a package called
``torchvision``, that has data loaders for common datasets such as
Imagenet, CIFAR10, MNIST, etc. and data transformers for images, viz.,
``torchvision.datasets`` and ``torch.utils.data.DataLoader``.

This provides a huge convenience and avoids writing boilerplate code.

For this tutorial, we will use the MNIST dataset.
It is a dataset of handwritten digits which is widely used in the field of machine learning.
It has the classes '0' to '9'.
The images in MNIST are of size 1x28x28, i.e. 1-channel images of 28x28 pixels in size.


Training an image classifier
----------------------------

We will do the following steps in order:

1. Load and normalizing the MNIST training and test datasets using
   ``torchvision``
2. Define a network
3. Define a loss function
4. Train the network on the training data
5. Test the network on the test data

## 1. Loading and normalizing MNIST

Using ``torchvision``, it’s extremely easy to load MNIST.



In [ ]:
import torch
from torchvision import datasets, transforms

The output of torchvision datasets are PILImage images of range [0, 1].
We transform them to Tensors of normalized range [-1, 1].
<div class="alert alert-info"><h4>Note</h4><p>If running on Windows and you get a BrokenPipeError, try setting
    the num_worker of torch.utils.data.DataLoader() to 0.</p></div>



In [ ]:
#여기서는 훈련용 데이터셋(trainset)과 테스트용 데이터셋(testset)을 준비하고 이 데이터셋의 모든 이미지를 텐서로 변한함

transform=transforms.Compose([ #transorm이라는 객체를 생성해서 여러개으 변환을 순서대로 연결하여 하나의 변환 파이프라인으로 만드는거임
    transforms.ToTensor(), # numpy배열 형태인 이미지를 pytorch의 torch.tensor타입으로 변환
    transforms.Normalize((0.5,), (0.5,)) # tensor의 픽셀 값들을 정규화(Normalization)함
    ])
#여기서 Normalization(정규화)는 각 채널(MNIST는 흑백이므로 채널이 1개)의 모든 픽셀 값 x를 아래와 같은 공식을 사용하여 변환함
#표준편차(0.5) / x−평균(0.5)

trainset = datasets.MNIST('./data', train=True, download=True,
                   transform=transform)
#datasets.MNIST() - pytorch의 MINIST데이터셋 클래스를 호출
#./data는 현재 디렉토리 아래 data폴더에 저장함.
#train=True로 훈련(Train) 데이터셋을 불러오도록 지정(60,000개의 이미지)
#download=True 해당 경로에 파일이 없다면 자동으로 인터넷에서 다운로드하도록 만듬
testset = datasets.MNIST('./data', train=False,
                         transform=transform)
#train=False: 모델의 성능을 평가(Test)하기 위한 데이터셋을 불러옴 (10,000개의 이미지).
#다운로드는 한 번만 하면 되므로 여기서는 download=True가 생략되거나 있어도 무방함.

100%|██████████| 9.91M/9.91M [00:00<00:00, 19.9MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 475kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.41MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 10.2MB/s]


In [ ]:
# Training settings 여기는 딥러닝 모델 훈련 환경을 설정하고 위에서 준비한 데이터셋(trainset,testset)을 모델에 효율적으로 공급하도록 데이터로더(DataLoader)를 생성함
batch_size = 64 # batch_size : train단계에서 한번에 처리할 데이터 샘플의 개수를 지저. 숫자가 클수록 GPU메모리를 많이 사용하지만 훈련 속도가 빨라지고 경사하강의 안정성이 향상될 수 있음
test_batch_size = 1000 #test_batch_size : test단계에서 한번에 처리할 데이터 샘플의 개수. 평가시에는 메모리 사용에 덜 민감해서 보통 train_batch보다 크게 잡음
no_cuda = False # 쿠다를 비활성화할지 설정 False라서 기본적으로 GPU를 사용하겠다는 의미
seed = 1 #난수 생성 seed를 1로 고정하여, 모델을 초기화하거나 데이터를 섞을 때마다 동일한 결과가 나오도록 보장(재현성 확보)
input_size = 28*28 # 784 - MINIST 이미지의 픽셀 수(가로28 세로28)
num_classes = 10 # MINIST 데이터셋의 분류 대상 클래스 수 10개(0~9)

use_cuda = not no_cuda and torch.cuda.is_available() # no_cuda가 False고 pytorch가 사용할 수 있는 CUDA가 있다면 use_cuda는 True가 됨

torch.manual_seed(seed) #위에서 설정한 시드를 pytorch의 난수 생성기에 적용하여, 실행할 때마다 동일한 경과를 얻도록 함

device = torch.device("cuda" if use_cuda else "cpu") #train에 사용할 device를 정의. GPU가 있으면 cuda로 아니면 cpu로 하면 됨
# 이제 모델과 데이터를 모두 이 장치로 이동시면 훈련이 시작됨

kwargs = {} #여기는 GPU(use_cuda가 True 일때) 환경에서 데이터 로딩 속도를 높이기 위한 추가적인 옵션을 kwargs 딕셔너리에 설정
if use_cuda: #GPU를 사용하면
    kwargs.update({'num_workers': 1,#데이터 로딩을 병렬로 처리하는 하위 프로세스(Worker)의 개수를 1개로 지정 - 데이터를 GPU가 옮기는 동안 CPU가 다음 데이터를 미리 준비하게 하여 대기 시간을 줄임
                   'pin_memory': True}) # 데이터를 CPU메모리가 아닌 고정된(pinned)메모리에 로드하도록 지시. 이 메모리는 GPU가 데이터에 더 빠르게 접근하고 전송할 수 있도록 최적화되어 있어 데이터 전송 속도를 높힘
# 이제 최종적으로 DataLoader를 생성
train_loader = torch.utils.data.DataLoader(dataset=trainset, batch_size=batch_size, shuffle=True, **kwargs) #tran_loader 생성
# dataset=trainset - 이전에 준비한 train dataset을 지정. batch_size=batch_size - 훈련 배치 크기(64)를 적용
# Shuffle=True - train data는 한 epoch가 끝날 때마다 데이터를 랜덤하게 섞어주어(Shuffling) 모델이 데이터 순서에 의존하지 않고 일반화 능력을 키우도록 도와줌
# **kwargs - 위에 설정한 GPU 최적화 옵션(ex:pin_memory)을 데이터 로더에 전달
test_loader = torch.utils.data.DataLoader(dataset=testset, batch_size=test_batch_size, shuffle=False, **kwargs) #test_loader 생성
#shuffle_False를 제외하고 train_loader와 비슷 - test data는 순서를 섞을 필요가 없어서 Shuffle을 보통 False로 둠


## 2. Define a network

In this assignment, we will use logistic regression model

In [ ]:
# pytorch에서 신경망(net)의 가장 기본적인 층(Layer)을 정의하고 이를 device(GPU)로 이동
net = nn.Linear(input_size, num_classes) #input_size - Layer로 들어오는 입력 뉴런의 개수 num_classes - layer에서 나가는 출력 뉴런의 개수(분류해야할 클래스의 개수와 같음)

net = net.to(device) # 방금 정의한 net 모델을 device(GPU)로 이동시킴
#훈련 속도를 높히기 위해 모델을 GPU로 이동시키는 것은 필수. 데이터(input)와 모델(net)이 같은 장치에 있어서 pytorch 연산이 원할하게 이루어짐

## 3. Define a Loss function and optimizer
Let's use a cross entropy loss and SGD with momentum.


In [ ]:
#여기서는 pytorch 딥러닝 모델의 학습을 위해 Loss Function과 Optimizer를 정의
import torch.optim as optim

criterion = nn.CrossEntropyLoss() #Loss를 꼐산할때 주로 criterion이라는 변수명을 사용하고 CrossEntropyLoss()이거는 수업때 배운 CrossEntropy(내부에 softmax도 포함되서 로짓을 그대로 입력하면 됨)
# 모델의 예측값(로짓)과 실제 정답 레이블을 비교하여 Loss를 계산. 이 loss를 모델이 학습해야함
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9) # 최적화는 보통 optimizer 이름으로 변수를 선언, SGD는 수업때 배운 경사 하강법
#gradient를 사용하여 신경망의 가중치와 편향(weight, bias)를 최적화 도구에 전달하여. 이 값들을 업데이트하도록 지정

## 4. Train the network

This is when things start to get interesting.
We simply have to loop over our data iterator, and feed the inputs to the
network and optimize.



In [ ]:
# training settings
#여기는 PyTorch 모델 훈련의 전반적인 흐름과 기록 방식을 설정하는 Hyperparameters를 정의. 학습의 횟수, 기록 주기, 모델 저장 여부를 설정함
epochs = 10 #train dataset을 반복하여 학습할 횟수. 10이면 모델은 전ㄴ체 데이터셋을 10번 보면서 weight를 업데이트함
log_interval = 100 # 훈련 진행 상황(ex:현재 loss 값)을 기록하거나 출력할 주기. 훈련 루프 내에서 이 값이 배치 수에 해당하면, 매 100번째 배치마다 현재의 loss나 진행 상태를 화면에 표시함
save_model = True # 훈련이 완료된 후, 학습된 모델이 최종적으로 조정된 weight와 bias들을 파일로 저장할지 여부를 결정함. 이 값이 True면 나중에 모델을 불러와 사용할 수 있도록 파일로 저장

In [ ]:
# 여기서는 DL model에 1epoch를 훈련시킬때 어떻게 할지 정의함(train_epoch)
def train_epoch(model, device, train_loader, optimizer, criterion, epoch): #훈련에 필요한 모든 요소(model, device, data_loader(train loader), optimizer(SGD경사하강법), criterion(CrossEntropyLoss), 현재 epoch번호)를 입력으로 받는 함수를 정의
    model.train() # 모델을 trainging mode로 설정
    for batch_idx, (data, target) in enumerate(train_loader): # 데이터 로더(train_loader를 반복)
    #반복할 때마다 data_loader는 한 묶음의 data와 그에 해당하는 target(lable)을 batch단위로 변환, batch_dix는 현재 batch의 번호
        # TODO: training code which optimizes model
        ##### YOUR CODE START #####
        data, target = data.to(device), target.to(device) #CPU에서 load된 batch와 data, target(lable)을 device(GPU)로 이동시킴. model과 data는 반드시 같은 device에 있어야 연산이 가능함
        optimizer.zero_grad() #gradient를 0으로 초기화함
        output = model(data.view(data.size(0), -1)) # Flatten the input for linear layer 여기서 view 함수는 PyTorch 텐서의 데이터는 유지하고 크기(shape) 변경하는 함수. 대부분의 Liner Layer이나 최종 분류 층은 input data를 1차원 벡터로 받도록 설계 돼있음
# input data를 model에 넣어 output(로짓)값을 얻음. data.view(data.size(0), -1) - 이거는 2차원 이미지(28*28)를 선형층(Liner Layer)의 입력에 맞게 1차원 백터(784)로 평탄화(Flatten)하는 역할임
        loss = criterion(output, target) #loss 계산. 예측값(output)과 정답(target)을 criterion(Optimizer)에 넣어 loss를 계산
        loss.backward() #backward. 계산된 loss를 바탕으로 신경망(net)의 모든 weight에 대한 gradient를 계산하고 저장함.
        optimizer.step() #optimizer가 계산된 gradient와 learning rate(학습률)을 사용하여 moodel의 weight와 bias를 실제로 업데이트함.
        ##### YOUR CODE END #####

        if batch_idx % log_interval == 0: #batch_idx가 log_interva(위에서 100으로 잡음)의 배수일 때마다, 훈련 진행 상황을 출력함.
            print(f'Train Epoch: {epoch} [{batch_idx * len(data)}/{len(train_loader.dataset)} ({(100. * batch_idx / len(train_loader)):.0f}%)]\tLoss: {loss.item():.6f}')
        #출력 내용은 Train Epoch: {epoch} : 현재 훈련중인 epoch 번호, [{batch_idx * len(data)}/{len(train_loader.dataset)} : 현재까지 처리한 data sample 수 / 전체 train dataset의 크기.
        #{(100. * batch_idx / len(train_loader)):.0f}% : 현재 epoch에서 진행된 데이터 처리 비율(%). Loss: {loss.item():.6f}: 현재 batch의 loss 값을 소수점 6자리까지 출력. (loss.item()은 텐서에서 실제 스칼라 값만 추출함.)

In [ ]:
#여기서는 성능을 평가하는 test를 정의함. 모델을 훈련시키는 train_epoch와 달리, 이 함수는 weight를 업데이트하지 않고 오직 예측의 정확성과 loss만을 계산함.
def test(model, device, test_loader, criterion): #test 함수 정의. model과 device, 위에서 정의한 test_loader, 우에서 정의한 criterion(Optimizer)을 입력받음.
    model.eval() #model을 평가모드로 설정함(evaluation mode)
    test_loss = 0.0 # test전용인 전체 테스트셋에 대한 총loss를 기록하기 위해 0으로 초기화
    correct = 0 # 정답의 개수도 기록을 위해 0으로 초기화
    with torch.no_grad(): #이 블록 안에서 실행되는 모든 연산에 대해 gradient 계산 및 저장을 비활성화(모델에 적용시키는것이 아닌, 성능을 평가하기 위한 test기 때문에 backward에 대한 grad를 계산할 필요가 없고 이를 비활성화 하면 GPU메모리가 절약되고 연산 속도가 빨라짐)
        for data, target in test_loader: #test data loader를 반복하여 batch단위로 data와 target을 가져옴.
            # TODO: test code which evaluates model
            ##### YOUR CODE START #####
            data, target = data.to(device), target.to(device) #data와 target을 device로 이동
            output = model(data.view(data.size(0), -1)) # Flatten the input for linear layer 데이터를 Flatten하여 model에 입력하고 예측값인 로짓(output)을 얻는다.weight나 bias에 대한 업데이트는 일어나지 않음
            test_loss += criterion(output, target).item() #현재 batch의 loss를 계산하고 이 값을 전체 test_loss에 누적함. .item()은 pytorch 텐서에서 순수한 python 숫자 값을 추출함.
            pred = output.argmax(dim=1, keepdim=True) # get the index of the max log-probability 모델 출력(output,로짓)에서 가장 큰 값의 인덱스 위치를 찾음. 이 인덱스가 model의 최종 예측 클래스가 됨. dim = 1은 클래스 차원에서 가장 큰 값을 찾으라는 의미
            correct += pred.eq(target.view_as(pred)).sum().item() # 모델의 예측(pred)이 target과 같은지 비교하여 T/F(1/0)텐서로 만듬. sum()으로 T(1)의 개수, 즉 정답의 개수를 모두 합산, 이 값을 전체 correct 변수에 누적함.
            ##### YOUR CODE END #####

    test_loss /= len(test_loader.dataset) #누적된 총 loss를 전체 테스트 데이터 개수로 나누어 평균 loss를 계산

    print(f'\nTest set: Average loss: {test_loss:.4f}, Accuracy: {correct}/{len(test_loader.dataset)} ({(100. * correct / len(test_loader.dataset)):.2f}%)\n')
    #계산된 평균loss과 정답 개수, 최종 정확도(Accuracy)를 %로 출력하여 모델의 성능을 출력함

In [ ]:
#이제부터 지금까지 정의한 모든 구성요소(train model, data loader, 훈련/평가 함수)를 사용해서 실제로 신경망의 훈련과 평가를 함.

for epoch in range(1, epochs + 1): #이전에 설정했던 epochs인 10 횟수만큼 반복
    train_epoch(net, device, train_loader, optimizer, criterion, epoch) #이전에 정의했던 1 epoch 훈련 함수를 호출.
    #이전에 만들어둔 net(신경망 모델), device(GPU), train_loader(훈련 데이터를 배치 단위로 묶어서 공급하는 도구), optimizer(가중치 업데이트를 담당하는 최적화 도구SGD 경사하강법이었음), criterion(loss를 계산하는 함수 - crossEntropyLoss 였음), epoch(훈련 상황을 보여주는 epoch 번호)

test(net, device, test_loader, criterion) # 훈련 루프가 완료된 후 (epoch만큼 학습이 끝난 후) 모델의 성능을 평가하는 함수 호출(바로 위에서 만든 평가 함수)

Train Epoch: 1 [0/60000 (0%)]	Loss: 2.569596
Train Epoch: 1 [6400/60000 (11%)]	Loss: 0.823095
Train Epoch: 1 [12800/60000 (21%)]	Loss: 0.628176
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.705135
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.504758
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.454715
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.409975
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.517998
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.392972
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.479948
Train Epoch: 2 [0/60000 (0%)]	Loss: 0.478568
Train Epoch: 2 [6400/60000 (11%)]	Loss: 0.364254
Train Epoch: 2 [12800/60000 (21%)]	Loss: 0.482242
Train Epoch: 2 [19200/60000 (32%)]	Loss: 0.306786
Train Epoch: 2 [25600/60000 (43%)]	Loss: 0.291108
Train Epoch: 2 [32000/60000 (53%)]	Loss: 0.376337
Train Epoch: 2 [38400/60000 (64%)]	Loss: 0.606430
Train Epoch: 2 [44800/60000 (75%)]	Loss: 0.484890
Train Epoch: 2 [51200/60000 (85%)]	Loss: 0.403751
Train Epoch: 2 [57600/60000 (96%)]	Loss: 0.253343
Train Epoch:

Let's quickly save our trained model:



In [ ]:
if save_model:
    torch.save(net.state_dict(), "mnist_net.pt")